import Head from "next/head";
import CardSection from "../components/cardSection/Index.js";
import Header from "../components/header/Index.js";
import InfoSection from "../components/infoSection/Index.js";
import FooterSection from "../components/footerSection/Index.js";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <Header />
        <InfoSection />
        <CardSection />
        <FooterSection />
      </main>
    </>
  );
}
